// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/like/mq/v1/like.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "harmoni/api/common/object/v1"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectType v1.ObjectType          `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=object.ObjectType" json:"object_type,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BaseMessage) Reset() {
	*x = BaseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_like_mq_v1_like_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMessage) ProtoMessage() {}

func (x *BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_mq_v1_like_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMessage.ProtoReflect.Descriptor instead.
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return file_api_like_mq_v1_like_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMessage) GetObjectType() v1.ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return v1.ObjectType(0)
}

func (x *BaseMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LikeCreatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseMessage  *BaseMessage `protobuf:"bytes,1,opt,name=base_message,json=baseMessage,proto3" json:"base_message,omitempty"`
	UserId       int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId int64        `protobuf:"varint,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	LikingId     int64        `protobuf:"varint,4,opt,name=liking_id,json=likingId,proto3" json:"liking_id,omitempty"`
	ObjectId     int64        `protobuf:"varint,5,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	IsCancel     bool         `protobuf:"varint,6,opt,name=is_cancel,json=isCancel,proto3" json:"is_cancel,omitempty"`
}

func (x *LikeCreatedMessage) Reset() {
	*x = LikeCreatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_like_mq_v1_like_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeCreatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCreatedMessage) ProtoMessage() {}

func (x *LikeCreatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_mq_v1_like_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCreatedMessage.ProtoReflect.Descriptor instead.
func (*LikeCreatedMessage) Descriptor() ([]byte, []int) {
	return file_api_like_mq_v1_like_proto_rawDescGZIP(), []int{1}
}

func (x *LikeCreatedMessage) GetBaseMessage() *BaseMessage {
	if x != nil {
		return x.BaseMessage
	}
	return nil
}

func (x *LikeCreatedMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeCreatedMessage) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *LikeCreatedMessage) GetLikingId() int64 {
	if x != nil {
		return x.LikingId
	}
	return 0
}

func (x *LikeCreatedMessage) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *LikeCreatedMessage) GetIsCancel() bool {
	if x != nil {
		return x.IsCancel
	}
	return false
}

var File_api_like_mq_v1_like_proto protoreflect.FileDescriptor

var file_api_like_mq_v1_like_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x6d, 0x71, 0x2f, 0x76, 0x31,
	0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x69, 0x6b,
	0x65, 0x2e, 0x6d, 0x71, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0b, 0x42,
	0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe6, 0x01, 0x0a, 0x12, 0x4c,
	0x69, 0x6b, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x6d,
	0x71, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x69, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x6c, 0x69, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x42, 0x1b, 0x5a, 0x19, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x6d, 0x71, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_like_mq_v1_like_proto_rawDescOnce sync.Once
	file_api_like_mq_v1_like_proto_rawDescData = file_api_like_mq_v1_like_proto_rawDesc
)

func file_api_like_mq_v1_like_proto_rawDescGZIP() []byte {
	file_api_like_mq_v1_like_proto_rawDescOnce.Do(func() {
		file_api_like_mq_v1_like_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_like_mq_v1_like_proto_rawDescData)
	})
	return file_api_like_mq_v1_like_proto_rawDescData
}

var file_api_like_mq_v1_like_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_like_mq_v1_like_proto_goTypes = []interface{}{
	(*BaseMessage)(nil),           // 0: like.mq.v1.BaseMessage
	(*LikeCreatedMessage)(nil),    // 1: like.mq.v1.LikeCreatedMessage
	(v1.ObjectType)(0),            // 2: object.ObjectType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_like_mq_v1_like_proto_depIdxs = []int32{
	2, // 0: like.mq.v1.BaseMessage.object_type:type_name -> object.ObjectType
	3, // 1: like.mq.v1.BaseMessage.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: like.mq.v1.LikeCreatedMessage.base_message:type_name -> like.mq.v1.BaseMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_like_mq_v1_like_proto_init() }
func file_api_like_mq_v1_like_proto_init() {
	if File_api_like_mq_v1_like_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_like_mq_v1_like_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_like_mq_v1_like_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeCreatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_like_mq_v1_like_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_like_mq_v1_like_proto_goTypes,
		DependencyIndexes: file_api_like_mq_v1_like_proto_depIdxs,
		MessageInfos:      file_api_like_mq_v1_like_proto_msgTypes,
	}.Build()
	File_api_like_mq_v1_like_proto = out.File
	file_api_like_mq_v1_like_proto_rawDesc = nil
	file_api_like_mq_v1_like_proto_goTypes = nil
	file_api_like_mq_v1_like_proto_depIdxs = nil
}
