// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: api/like/grpc/v1/like.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "harmoni/api/common/object/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Like_Like_FullMethodName           = "/like.Like/Like"
	Like_UserLikeList_FullMethodName   = "/like.Like/UserLikeList"
	Like_ObjectLikeList_FullMethodName = "/like.Like/ObjectLikeList"
	Like_LikeCount_FullMethodName      = "/like.Like/LikeCount"
	Like_ListLikeCount_FullMethodName  = "/like.Like/ListLikeCount"
)

// LikeClient is the client API for Like service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeClient interface {
	Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeReply, error)
	UserLikeList(ctx context.Context, in *UserLikeListRequest, opts ...grpc.CallOption) (*LikeListReply, error)
	ObjectLikeList(ctx context.Context, in *ObjectLikeListRequest, opts ...grpc.CallOption) (*LikeListReply, error)
	LikeCount(ctx context.Context, in *v1.Object, opts ...grpc.CallOption) (*LikeCountReply, error)
	ListLikeCount(ctx context.Context, in *ListLikeCountRequest, opts ...grpc.CallOption) (*ListLikeCountReply, error)
}

type likeClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeClient(cc grpc.ClientConnInterface) LikeClient {
	return &likeClient{cc}
}

func (c *likeClient) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeReply, error) {
	out := new(LikeReply)
	err := c.cc.Invoke(ctx, Like_Like_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) UserLikeList(ctx context.Context, in *UserLikeListRequest, opts ...grpc.CallOption) (*LikeListReply, error) {
	out := new(LikeListReply)
	err := c.cc.Invoke(ctx, Like_UserLikeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) ObjectLikeList(ctx context.Context, in *ObjectLikeListRequest, opts ...grpc.CallOption) (*LikeListReply, error) {
	out := new(LikeListReply)
	err := c.cc.Invoke(ctx, Like_ObjectLikeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) LikeCount(ctx context.Context, in *v1.Object, opts ...grpc.CallOption) (*LikeCountReply, error) {
	out := new(LikeCountReply)
	err := c.cc.Invoke(ctx, Like_LikeCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) ListLikeCount(ctx context.Context, in *ListLikeCountRequest, opts ...grpc.CallOption) (*ListLikeCountReply, error) {
	out := new(ListLikeCountReply)
	err := c.cc.Invoke(ctx, Like_ListLikeCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServer is the server API for Like service.
// All implementations must embed UnimplementedLikeServer
// for forward compatibility
type LikeServer interface {
	Like(context.Context, *LikeRequest) (*LikeReply, error)
	UserLikeList(context.Context, *UserLikeListRequest) (*LikeListReply, error)
	ObjectLikeList(context.Context, *ObjectLikeListRequest) (*LikeListReply, error)
	LikeCount(context.Context, *v1.Object) (*LikeCountReply, error)
	ListLikeCount(context.Context, *ListLikeCountRequest) (*ListLikeCountReply, error)
	mustEmbedUnimplementedLikeServer()
}

// UnimplementedLikeServer must be embedded to have forward compatible implementations.
type UnimplementedLikeServer struct {
}

func (UnimplementedLikeServer) Like(context.Context, *LikeRequest) (*LikeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedLikeServer) UserLikeList(context.Context, *UserLikeListRequest) (*LikeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLikeList not implemented")
}
func (UnimplementedLikeServer) ObjectLikeList(context.Context, *ObjectLikeListRequest) (*LikeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectLikeList not implemented")
}
func (UnimplementedLikeServer) LikeCount(context.Context, *v1.Object) (*LikeCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeCount not implemented")
}
func (UnimplementedLikeServer) ListLikeCount(context.Context, *ListLikeCountRequest) (*ListLikeCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLikeCount not implemented")
}
func (UnimplementedLikeServer) mustEmbedUnimplementedLikeServer() {}

// UnsafeLikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServer will
// result in compilation errors.
type UnsafeLikeServer interface {
	mustEmbedUnimplementedLikeServer()
}

func RegisterLikeServer(s grpc.ServiceRegistrar, srv LikeServer) {
	s.RegisterService(&Like_ServiceDesc, srv)
}

func _Like_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).Like(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_UserLikeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLikeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).UserLikeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_UserLikeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).UserLikeList(ctx, req.(*UserLikeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_ObjectLikeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectLikeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ObjectLikeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ObjectLikeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ObjectLikeList(ctx, req.(*ObjectLikeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_LikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).LikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_LikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).LikeCount(ctx, req.(*v1.Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_ListLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLikeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ListLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ListLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ListLikeCount(ctx, req.(*ListLikeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_ServiceDesc is the grpc.ServiceDesc for Like service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "like.Like",
	HandlerType: (*LikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _Like_Like_Handler,
		},
		{
			MethodName: "UserLikeList",
			Handler:    _Like_UserLikeList_Handler,
		},
		{
			MethodName: "ObjectLikeList",
			Handler:    _Like_ObjectLikeList_Handler,
		},
		{
			MethodName: "LikeCount",
			Handler:    _Like_LikeCount_Handler,
		},
		{
			MethodName: "ListLikeCount",
			Handler:    _Like_ListLikeCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/like/grpc/v1/like.proto",
}
