// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/like/grpc/v1/like.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "harmoni/api/like/mq/v1"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LikeType     v1.LikeType `protobuf:"varint,1,opt,name=likeType,proto3,enum=like.mq.v1.LikeType" json:"likeType,omitempty"`
	UserID       int64       `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ObjectID     int64       `protobuf:"varint,3,opt,name=objectID,proto3" json:"objectID,omitempty"`
	TargetUserID int64       `protobuf:"varint,4,opt,name=targetUserID,proto3" json:"targetUserID,omitempty"`
	IsCancel     bool        `protobuf:"varint,5,opt,name=isCancel,proto3" json:"isCancel,omitempty"`
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_like_grpc_v1_like_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_grpc_v1_like_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_api_like_grpc_v1_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetLikeType() v1.LikeType {
	if x != nil {
		return x.LikeType
	}
	return v1.LikeType(0)
}

func (x *LikeRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LikeRequest) GetObjectID() int64 {
	if x != nil {
		return x.ObjectID
	}
	return 0
}

func (x *LikeRequest) GetTargetUserID() int64 {
	if x != nil {
		return x.TargetUserID
	}
	return 0
}

func (x *LikeRequest) GetIsCancel() bool {
	if x != nil {
		return x.IsCancel
	}
	return false
}

type LikeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikeReply) Reset() {
	*x = LikeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_like_grpc_v1_like_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReply) ProtoMessage() {}

func (x *LikeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_like_grpc_v1_like_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReply.ProtoReflect.Descriptor instead.
func (*LikeReply) Descriptor() ([]byte, []int) {
	return file_api_like_grpc_v1_like_proto_rawDescGZIP(), []int{1}
}

var File_api_like_grpc_v1_like_proto protoreflect.FileDescriptor

var file_api_like_grpc_v1_like_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c,
	0x69, 0x6b, 0x65, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x6d, 0x71,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3,
	0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x6d, 0x71, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x6b, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x22, 0x0b, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0x32, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x4c, 0x69, 0x6b,
	0x65, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1d, 0x5a, 0x1b, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_like_grpc_v1_like_proto_rawDescOnce sync.Once
	file_api_like_grpc_v1_like_proto_rawDescData = file_api_like_grpc_v1_like_proto_rawDesc
)

func file_api_like_grpc_v1_like_proto_rawDescGZIP() []byte {
	file_api_like_grpc_v1_like_proto_rawDescOnce.Do(func() {
		file_api_like_grpc_v1_like_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_like_grpc_v1_like_proto_rawDescData)
	})
	return file_api_like_grpc_v1_like_proto_rawDescData
}

var file_api_like_grpc_v1_like_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_like_grpc_v1_like_proto_goTypes = []interface{}{
	(*LikeRequest)(nil), // 0: like.LikeRequest
	(*LikeReply)(nil),   // 1: like.LikeReply
	(v1.LikeType)(0),    // 2: like.mq.v1.LikeType
}
var file_api_like_grpc_v1_like_proto_depIdxs = []int32{
	2, // 0: like.LikeRequest.likeType:type_name -> like.mq.v1.LikeType
	0, // 1: like.Like.Like:input_type -> like.LikeRequest
	1, // 2: like.Like.Like:output_type -> like.LikeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_like_grpc_v1_like_proto_init() }
func file_api_like_grpc_v1_like_proto_init() {
	if File_api_like_grpc_v1_like_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_like_grpc_v1_like_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_like_grpc_v1_like_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_like_grpc_v1_like_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_like_grpc_v1_like_proto_goTypes,
		DependencyIndexes: file_api_like_grpc_v1_like_proto_depIdxs,
		MessageInfos:      file_api_like_grpc_v1_like_proto_msgTypes,
	}.Build()
	File_api_like_grpc_v1_like_proto = out.File
	file_api_like_grpc_v1_like_proto_rawDesc = nil
	file_api_like_grpc_v1_like_proto_goTypes = nil
	file_api_like_grpc_v1_like_proto_depIdxs = nil
}
