// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.uber.org/zap"
	"harmoni/app/harmoni/internal/cron"
	"harmoni/app/harmoni/internal/handler"
	"harmoni/app/harmoni/internal/infrastructure/config"
	"harmoni/app/harmoni/internal/infrastructure/data"
	"harmoni/app/harmoni/internal/infrastructure/mq/publisher"
	"harmoni/app/harmoni/internal/pkg/app"
	"harmoni/app/harmoni/internal/pkg/filesystem"
	"harmoni/app/harmoni/internal/pkg/logger"
	"harmoni/app/harmoni/internal/pkg/middleware"
	"harmoni/app/harmoni/internal/pkg/snowflakex"
	"harmoni/app/harmoni/internal/repository/auth"
	"harmoni/app/harmoni/internal/repository/comment"
	"harmoni/app/harmoni/internal/repository/email"
	file2 "harmoni/app/harmoni/internal/repository/file"
	"harmoni/app/harmoni/internal/repository/follow"
	"harmoni/app/harmoni/internal/repository/like"
	"harmoni/app/harmoni/internal/repository/post"
	"harmoni/app/harmoni/internal/repository/tag"
	"harmoni/app/harmoni/internal/repository/unique"
	user2 "harmoni/app/harmoni/internal/repository/user"
	"harmoni/app/harmoni/internal/server/http"
	"harmoni/app/harmoni/internal/server/mq"
	"harmoni/app/harmoni/internal/service"
	comment2 "harmoni/app/harmoni/internal/usecase/comment"
	"harmoni/app/harmoni/internal/usecase/comment/events"
	email2 "harmoni/app/harmoni/internal/usecase/email"
	"harmoni/app/harmoni/internal/usecase/file"
	follow2 "harmoni/app/harmoni/internal/usecase/follow"
	like2 "harmoni/app/harmoni/internal/usecase/like"
	events2 "harmoni/app/harmoni/internal/usecase/like/events"
	post2 "harmoni/app/harmoni/internal/usecase/post"
	events3 "harmoni/app/harmoni/internal/usecase/post/events"
	tag2 "harmoni/app/harmoni/internal/usecase/tag"
	"harmoni/app/harmoni/internal/usecase/timeline"
	"harmoni/app/harmoni/internal/usecase/user"
	events4 "harmoni/app/harmoni/internal/usecase/user/events"
)

// Injectors from wire.go:

func initApplication(conf *config.Config, appConf *config.App, dbconf *config.DB, rdbconf *config.Redis, authConf *config.Auth, emailConf *config.Email, likeConf *config.Like, messageConf *config.MessageQueue, fileConf *config.FileStorage, logConf *config.Log) (*app.Application, func(), error) {
	zapLogger, err := logger.NewZapLogger(logConf)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := data.NewRedis(rdbconf)
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger := sugar(zapLogger)
	authRepo := auth.NewAuthRepo(client, sugaredLogger)
	authUseCase := user.NewAuthUseCase(authConf, authRepo, sugaredLogger)
	db, cleanup2, err := data.NewDB(dbconf, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	node, err := snowflakex.NewSnowflakeNode(appConf)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uniqueIDRepo := unique.NewUniqueIDRepo(node)
	userRepo := user2.NewUserRepo(db, client, uniqueIDRepo, sugaredLogger)
	emailRepo := email.NewEmailRepo(client)
	emailUsecase, err := email2.NewEmailUsecase(emailConf, emailRepo, sugaredLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	likeRepo := like.NewLikeRepo(likeConf, db, client, userRepo, sugaredLogger)
	policy := file.NewPolicy(fileConf)
	fileSystem, err := filesystem.NewFileSystem(policy, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fileRepo := file2.NewFileRepository(db, client, uniqueIDRepo, sugaredLogger)
	fileUseCase := file.NewFileUseCase(appConf, client, fileConf, fileSystem, fileRepo, sugaredLogger)
	userUseCase := user.NewUserUseCase(likeRepo, userRepo, authUseCase, fileUseCase, sugaredLogger)
	accountUsecase := user.NewAccountUsecase(emailConf, authUseCase, userRepo, emailUsecase, userUseCase, zapLogger)
	accountService := service.NewAccountService(accountUsecase, sugaredLogger)
	jwtAuthMiddleware := middleware.NewJwtAuthMiddleware(authUseCase)
	accountHandler := handler.NewAccountHandler(accountService, jwtAuthMiddleware, sugaredLogger)
	tagRepo := tag.NewTagRepo(db, client, uniqueIDRepo, sugaredLogger)
	followRepo := follow.NewFollowRepo(db, userRepo, tagRepo, uniqueIDRepo, sugaredLogger)
	tagUseCase := tag2.NewTagUseCase(tagRepo, sugaredLogger)
	followUseCase := follow2.NewFollowUseCase(followRepo, userUseCase, tagUseCase, sugaredLogger)
	followService := service.NewFollowService(followUseCase, userUseCase, sugaredLogger)
	followHandler := handler.NewFollowHandler(followService, sugaredLogger)
	fileService := service.NewFileService(fileUseCase, userUseCase, sugaredLogger)
	fileHandler := handler.NewFileHandler(fileService, sugaredLogger)
	userService := service.NewUserService(userUseCase, authUseCase, accountUsecase, sugaredLogger)
	userHandler := handler.NewUserHandler(userService)
	postRepo := post.NewPostRepo(db, client, tagRepo, uniqueIDRepo, sugaredLogger)
	postUseCase := post2.NewPostUseCase(postRepo, likeRepo, userUseCase, tagUseCase, sugaredLogger)
	postService := service.NewPostService(postUseCase, tagUseCase, sugaredLogger)
	postHandler := handler.NewPostHandler(postService)
	tagService := service.NewTagService(tagUseCase, sugaredLogger)
	tagHandler := handler.NewTagHandler(tagService)
	commentRepo := comment.NewCommentRepo(db, client, uniqueIDRepo, sugaredLogger)
	commentUseCase := comment2.NewCommentUseCase(commentRepo, likeRepo, userRepo, fileUseCase, sugaredLogger)
	commentService := service.NewCommentService(commentUseCase, sugaredLogger)
	commentHandler := handler.NewCommentHandler(commentService)
	messagePublisher, err := publisher.NewPublisher(messageConf, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jsonPublisher := publisher.NewJSONPublisher(messagePublisher)
	likeUsecase, cleanup3, err := like2.NewLikeUsecase(messageConf, likeRepo, postUseCase, commentRepo, userRepo, sugaredLogger, jsonPublisher)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	likeService := service.NewLikeUsecase(likeUsecase, sugaredLogger)
	likeHandler := handler.NewLikeHandler(likeService, sugaredLogger)
	timeLinePullUsecase := timeline.NewTimeLineUsecase(followRepo, postUseCase, sugaredLogger)
	timeLineService := service.NewTimeLineService(timeLinePullUsecase, sugaredLogger)
	timeLineHandler := handler.NewTimeLineHandler(timeLineService)
	harmoniAPIRouter := http.NewHarmoniAPIRouter(accountHandler, followHandler, fileHandler, userHandler, postHandler, tagHandler, commentHandler, likeHandler, timeLineHandler)
	fiberExecutor := http.NewHTTPServer(appConf, zapLogger, harmoniAPIRouter, jwtAuthMiddleware)
	scheduledTaskManager, cleanup4, err := cron.NewScheduledTaskManager(likeConf, jsonPublisher, likeUsecase, sugaredLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	commentEventsHandler := events.NewCommentEventsHandler(commentRepo)
	likeEventsHandler := events2.NewLikeEventsHandler(likeRepo)
	postEventsHandler := events3.NewPostEventsHandler(postRepo)
	userEventsHandler := events4.NewUserEventsHandler(userRepo)
	router, err := mq.NewMQRouter(messageConf, commentEventsHandler, likeEventsHandler, postEventsHandler, userEventsHandler, zapLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mqExecutor := mq.NewExecutor(router)
	application := newApplication(conf, fiberExecutor, scheduledTaskManager, mqExecutor, sugaredLogger)
	return application, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func sugar(l *zap.Logger) *zap.SugaredLogger {
	return l.Sugar()
}
