// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: internal/pkg/paginator/page.proto

package paginator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_paginator_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_paginator_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_paginator_page_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *PageRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PageRely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current int64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size    int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total   int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PageRely) Reset() {
	*x = PageRely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_paginator_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRely) ProtoMessage() {}

func (x *PageRely) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_paginator_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRely.ProtoReflect.Descriptor instead.
func (*PageRely) Descriptor() ([]byte, []int) {
	return file_internal_pkg_paginator_page_proto_rawDescGZIP(), []int{1}
}

func (x *PageRely) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PageRely) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageRely) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_internal_pkg_paginator_page_proto protoreflect.FileDescriptor

var file_internal_pkg_paginator_page_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x33,
	0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x22, 0x4e, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x42, 0x20, 0x5a, 0x1e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_paginator_page_proto_rawDescOnce sync.Once
	file_internal_pkg_paginator_page_proto_rawDescData = file_internal_pkg_paginator_page_proto_rawDesc
)

func file_internal_pkg_paginator_page_proto_rawDescGZIP() []byte {
	file_internal_pkg_paginator_page_proto_rawDescOnce.Do(func() {
		file_internal_pkg_paginator_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_paginator_page_proto_rawDescData)
	})
	return file_internal_pkg_paginator_page_proto_rawDescData
}

var file_internal_pkg_paginator_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pkg_paginator_page_proto_goTypes = []interface{}{
	(*PageRequest)(nil), // 0: paginator.PageRequest
	(*PageRely)(nil),    // 1: paginator.PageRely
}
var file_internal_pkg_paginator_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pkg_paginator_page_proto_init() }
func file_internal_pkg_paginator_page_proto_init() {
	if File_internal_pkg_paginator_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_paginator_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_paginator_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_paginator_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pkg_paginator_page_proto_goTypes,
		DependencyIndexes: file_internal_pkg_paginator_page_proto_depIdxs,
		MessageInfos:      file_internal_pkg_paginator_page_proto_msgTypes,
	}.Build()
	File_internal_pkg_paginator_page_proto = out.File
	file_internal_pkg_paginator_page_proto_rawDesc = nil
	file_internal_pkg_paginator_page_proto_goTypes = nil
	file_internal_pkg_paginator_page_proto_depIdxs = nil
}
