// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: app/like/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	conf "harmoni/internal/conf"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App          *conf.App          `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	MessageQueue *conf.MessageQueue `protobuf:"bytes,2,opt,name=message_queue,json=messageQueue,proto3" json:"message_queue,omitempty"`
	Log          *conf.Log          `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Etcd         *conf.ETCD         `protobuf:"bytes,4,opt,name=etcd,proto3" json:"etcd,omitempty"`
	Db           *conf.DB           `protobuf:"bytes,5,opt,name=db,proto3" json:"db,omitempty"`
	Server       *conf.Server       `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	Redis        *conf.Redis        `protobuf:"bytes,7,opt,name=redis,proto3" json:"redis,omitempty"`
}

func (x *Conf) Reset() {
	*x = Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_like_internal_conf_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_app_like_internal_conf_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_app_like_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Conf) GetApp() *conf.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Conf) GetMessageQueue() *conf.MessageQueue {
	if x != nil {
		return x.MessageQueue
	}
	return nil
}

func (x *Conf) GetLog() *conf.Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Conf) GetEtcd() *conf.ETCD {
	if x != nil {
		return x.Etcd
	}
	return nil
}

func (x *Conf) GetDb() *conf.DB {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Conf) GetServer() *conf.Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Conf) GetRedis() *conf.Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

var File_app_like_internal_conf_conf_proto protoreflect.FileDescriptor

var file_app_like_internal_conf_conf_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x70, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x01,
	0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x03,
	0x61, 0x70, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x03,
	0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x65, 0x74, 0x63,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x45,
	0x54, 0x43, 0x44, 0x52, 0x04, 0x65, 0x74, 0x63, 0x64, 0x12, 0x18, 0x0a, 0x02, 0x64, 0x62, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x44, 0x42, 0x52,
	0x02, 0x64, 0x62, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x42, 0x35, 0x5a, 0x33,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63,
	0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_like_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_like_internal_conf_conf_proto_rawDescData = file_app_like_internal_conf_conf_proto_rawDesc
)

func file_app_like_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_like_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_like_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_like_internal_conf_conf_proto_rawDescData)
	})
	return file_app_like_internal_conf_conf_proto_rawDescData
}

var file_app_like_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_like_internal_conf_conf_proto_goTypes = []interface{}{
	(*Conf)(nil),              // 0: Conf
	(*conf.App)(nil),          // 1: conf.App
	(*conf.MessageQueue)(nil), // 2: conf.MessageQueue
	(*conf.Log)(nil),          // 3: conf.Log
	(*conf.ETCD)(nil),         // 4: conf.ETCD
	(*conf.DB)(nil),           // 5: conf.DB
	(*conf.Server)(nil),       // 6: conf.Server
	(*conf.Redis)(nil),        // 7: conf.Redis
}
var file_app_like_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: Conf.app:type_name -> conf.App
	2, // 1: Conf.message_queue:type_name -> conf.MessageQueue
	3, // 2: Conf.log:type_name -> conf.Log
	4, // 3: Conf.etcd:type_name -> conf.ETCD
	5, // 4: Conf.db:type_name -> conf.DB
	6, // 5: Conf.server:type_name -> conf.Server
	7, // 6: Conf.redis:type_name -> conf.Redis
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_app_like_internal_conf_conf_proto_init() }
func file_app_like_internal_conf_conf_proto_init() {
	if File_app_like_internal_conf_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_like_internal_conf_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_like_internal_conf_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_like_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_like_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_like_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_like_internal_conf_conf_proto = out.File
	file_app_like_internal_conf_conf_proto_rawDesc = nil
	file_app_like_internal_conf_conf_proto_goTypes = nil
	file_app_like_internal_conf_conf_proto_depIdxs = nil
}
