// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: app/harmoni/api/grpc/v1/user/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserBasic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *UserBasic) Reset() {
	*x = UserBasic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasic) ProtoMessage() {}

func (x *UserBasic) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasic.ProtoReflect.Descriptor instead.
func (*UserBasic) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserBasic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBasic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBasic) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBasicRequest) Reset() {
	*x = GetBasicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicRequest) ProtoMessage() {}

func (x *GetBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicRequest.ProtoReflect.Descriptor instead.
func (*GetBasicRequest) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBasicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListBasicsRequest) Reset() {
	*x = ListBasicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBasicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasicsRequest) ProtoMessage() {}

func (x *ListBasicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasicsRequest.ProtoReflect.Descriptor instead.
func (*ListBasicsRequest) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListBasicsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListBasicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserBasic `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *ListBasicsResponse) Reset() {
	*x = ListBasicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBasicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasicsResponse) ProtoMessage() {}

func (x *ListBasicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasicsResponse.ProtoReflect.Descriptor instead.
func (*ListBasicsResponse) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListBasicsResponse) GetUsers() []*UserBasic {
	if x != nil {
		return x.Users
	}
	return nil
}

type TokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserBasic `protobuf:"bytes,1,opt,name=user,proto3,oneof" json:"user,omitempty"`
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *TokenResponse) GetUser() *UserBasic {
	if x != nil {
		return x.User
	}
	return nil
}

var File_app_harmoni_api_grpc_v1_user_user_proto protoreflect.FileDescriptor

var file_app_harmoni_api_grpc_v1_user_user_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x70, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x47, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x3b, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x24, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x42, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x32, 0xb3, 0x01, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x15,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x21, 0x5a, 0x1f, 0x61, 0x70, 0x70, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_harmoni_api_grpc_v1_user_user_proto_rawDescOnce sync.Once
	file_app_harmoni_api_grpc_v1_user_user_proto_rawDescData = file_app_harmoni_api_grpc_v1_user_user_proto_rawDesc
)

func file_app_harmoni_api_grpc_v1_user_user_proto_rawDescGZIP() []byte {
	file_app_harmoni_api_grpc_v1_user_user_proto_rawDescOnce.Do(func() {
		file_app_harmoni_api_grpc_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_harmoni_api_grpc_v1_user_user_proto_rawDescData)
	})
	return file_app_harmoni_api_grpc_v1_user_user_proto_rawDescData
}

var file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_harmoni_api_grpc_v1_user_user_proto_goTypes = []interface{}{
	(*UserBasic)(nil),          // 0: user.UserBasic
	(*GetBasicRequest)(nil),    // 1: user.GetBasicRequest
	(*ListBasicsRequest)(nil),  // 2: user.ListBasicsRequest
	(*ListBasicsResponse)(nil), // 3: user.ListBasicsResponse
	(*TokenRequest)(nil),       // 4: user.TokenRequest
	(*TokenResponse)(nil),      // 5: user.TokenResponse
}
var file_app_harmoni_api_grpc_v1_user_user_proto_depIdxs = []int32{
	0, // 0: user.ListBasicsResponse.users:type_name -> user.UserBasic
	0, // 1: user.TokenResponse.user:type_name -> user.UserBasic
	1, // 2: user.User.GetBasic:input_type -> user.GetBasicRequest
	2, // 3: user.User.List:input_type -> user.ListBasicsRequest
	4, // 4: user.User.VerifyToken:input_type -> user.TokenRequest
	0, // 5: user.User.GetBasic:output_type -> user.UserBasic
	3, // 6: user.User.List:output_type -> user.ListBasicsResponse
	5, // 7: user.User.VerifyToken:output_type -> user.TokenResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_harmoni_api_grpc_v1_user_user_proto_init() }
func file_app_harmoni_api_grpc_v1_user_user_proto_init() {
	if File_app_harmoni_api_grpc_v1_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBasic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBasicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBasicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_harmoni_api_grpc_v1_user_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_harmoni_api_grpc_v1_user_user_proto_goTypes,
		DependencyIndexes: file_app_harmoni_api_grpc_v1_user_user_proto_depIdxs,
		MessageInfos:      file_app_harmoni_api_grpc_v1_user_user_proto_msgTypes,
	}.Build()
	File_app_harmoni_api_grpc_v1_user_user_proto = out.File
	file_app_harmoni_api_grpc_v1_user_user_proto_rawDesc = nil
	file_app_harmoni_api_grpc_v1_user_user_proto_goTypes = nil
	file_app_harmoni_api_grpc_v1_user_user_proto_depIdxs = nil
}
